name: Metrics
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: moabukar
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: moabukar
          template: classic
          base: header
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  lines:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes

  acti_comm:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: moabukar
          template: classic
          base: activity, community
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  iso_calender:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: moabukar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-habits.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          user: moabukar
          base: ""
          template: classic
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes

  issue_pr_lang:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: moabukar
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_followup: yes
          plugin_languages: yes

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: moabukar
          template: classic
          base: repositories
          config_timezone: ${{ secrets.USER_TIMEZONE }}
